// Biomanufacturing and BLiSS Resource Production
// WP14: Bell et al. (Space Policy, May 2026); Extraterrestrial infrastructures review (2026)

Alias: $loinc = http://loinc.org
Alias: $sct = http://snomed.info/sct
Alias: $ucum = http://unitsofmeasure.org

// =====================================================
// CODE SYSTEMS
// =====================================================

CodeSystem: BiomanufacturingProcessCS
Id: biomanufacturing-process-cs
Title: "Biomanufacturing Process Code System"
Description: "Biomanufacturing processes for in-situ resource utilization and life support"
* ^count = 6
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* ^status = #active
* #algae-photobioreactor "Algae Photobioreactor" "Photosynthetic algae cultivation for O2 production and biomass"
* #fermentation-bioreactor "Fermentation Bioreactor" "Microbial fermentation for food, pharmaceuticals, or biomaterials"
* #isru-processor "ISRU Processor" "In-situ resource utilization bioprocessing of regolith or atmosphere"
* #biocement-production "Biocement Production" "Microbially-induced calcium carbonate precipitation for construction"
* #pharmaceutical-synthesis "Pharmaceutical Synthesis" "On-demand biopharmaceutical production using engineered organisms"
* #biomass-conversion "Biomass Conversion" "Conversion of waste biomass to usable products"

CodeSystem: BLiSSOutputCS
Id: bliss-output-cs
Title: "BLiSS Output Code System"
Description: "Bioregenerative Life Support System (BLiSS) output types"
* ^count = 6
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* ^status = #active
* #o2-production "O2 Production" "Oxygen generated by photosynthetic organisms"
* #food-production "Food Production" "Edible biomass produced for crew nutrition"
* #water-recycling "Water Recycling" "Water recovered through biological treatment processes"
* #biofuel-production "Biofuel Production" "Fuel produced from biological feedstocks"
* #co2-fixation "CO2 Fixation" "Carbon dioxide removed from atmosphere by biological processes"
* #biomaterial-output "Biomaterial Output" "Structural or functional biomaterials produced"

CodeSystem: BiomanufacturingMetricCS
Id: biomanufacturing-metric-cs
Title: "Biomanufacturing Metric Code System"
Description: "Component codes for biomanufacturing output observations"
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* ^status = #active
* ^count = 3
* #output-quantity "Output Quantity" "Total output quantity (kg, L, mol)"
* #output-rate "Output Rate" "Production rate per day or per cycle"
* #energy-input "Energy Input" "Energy consumed by the process"

// =====================================================
// VALUE SETS
// =====================================================

ValueSet: BiomanufacturingProcessVS
Id: biomanufacturing-process-vs
Title: "Biomanufacturing Process Value Set"
Description: "Biomanufacturing process types"
* ^experimental = true
* ^status = #active
* include codes from system BiomanufacturingProcessCS

ValueSet: BLiSSOutputVS
Id: bliss-output-vs
Title: "BLiSS Output Value Set"
Description: "Bioregenerative life support output types"
* ^experimental = true
* ^status = #active
* include codes from system BLiSSOutputCS

// =====================================================
// PROFILES
// =====================================================

Profile: BioreactorDevice
Parent: Device
Id: bioreactor-device
Title: "Bioreactor Device"
Description: "Bioreactor device for in-situ biomanufacturing including photobioreactors and fermentation vessels"
* ^version = "1.0.0"
* ^status = #active

* type 1..1 MS
* type ^short = "Bioreactor type"

* status MS

* deviceName 0..* MS

* manufacturer 0..1 MS
* modelNumber 0..1 MS

* property 0..* MS
* property ^short = "Reactor properties (volume, temperature, culture type)"

* note 0..* MS
* note ^short = "Operational parameters and culture details"

* extension contains
    MissionContext named missionContext 0..1 MS

Profile: BiomanufacturingProcedure
Parent: Procedure
Id: biomanufacturing-procedure
Title: "Biomanufacturing Procedure"
Description: "Biomanufacturing process execution for ISRU or life support production"
* ^version = "1.0.0"
* ^status = #active

* status MS

* code 1..1 MS
* code from BiomanufacturingProcessVS (extensible)
* code ^short = "Biomanufacturing process type"

* subject 1..1 MS
* subject ^short = "Habitat or mission where process is performed"

* performed[x] 0..1 MS
* performed[x] only dateTime or Period

* usedReference 0..* MS
* usedReference ^short = "Bioreactor device used"

* outcome 0..1 MS
* outcome ^short = "Process outcome"

* note 0..* MS
* note ^short = "Process parameters, yield, and conditions"

* extension contains
    MissionContext named missionContext 0..1 MS and
    GravityContext named gravityContext 0..1 MS

Profile: BLiSSResourceOutput
Parent: Observation
Id: bliss-resource-output
Title: "BLiSS Resource Output"
Description: "Observation of bioregenerative life support system resource output quantities and rates"
* ^version = "1.0.0"
* ^status = #active

* status MS

* code 1..1 MS
* code from BLiSSOutputVS (extensible)
* code ^short = "BLiSS output type"

* subject 1..1 MS
* subject ^short = "Habitat or bioreactor producing the output"

* effective[x] 0..1 MS
* effective[x] only dateTime or Period

* component ^slicing.discriminator.type = #pattern
* component ^slicing.discriminator.path = "code"
* component ^slicing.rules = #open

* component contains
    outputQuantity 0..1 MS and
    outputRate 0..1 MS and
    energyInput 0..1 MS

* component[outputQuantity].code = BiomanufacturingMetricCS#output-quantity "Output Quantity"
* component[outputQuantity].value[x] only Quantity
* component[outputQuantity].valueQuantity ^short = "Total output quantity (kg, L, mol)"

* component[outputRate].code = BiomanufacturingMetricCS#output-rate "Output Rate"
* component[outputRate].value[x] only Quantity
* component[outputRate].valueQuantity ^short = "Production rate (per day or per cycle)"

* component[energyInput].code = BiomanufacturingMetricCS#energy-input "Energy Input"
* component[energyInput].value[x] only Quantity
* component[energyInput].valueQuantity.system = $ucum
* component[energyInput].valueQuantity.code = #kW
* component[energyInput].valueQuantity ^short = "Energy input in kilowatts"

* extension contains
    MissionContext named missionContext 0..1 MS and
    GravityContext named gravityContext 0..1 MS

Profile: BiologicalFeedstock
Parent: Substance
Id: biological-feedstock
Title: "Biological Feedstock"
Description: "Biological feedstock or bioproduct used in or produced by biomanufacturing processes"
* ^version = "1.0.0"
* ^status = #active

* status MS

* code 1..1 MS
* code ^short = "Feedstock or bioproduct identity"

* description 0..1 MS
* description ^short = "Description of the biological material"

* category 0..* MS
* category ^short = "Classification (feedstock, intermediate, product)"

* instance 0..* MS
* instance.quantity 0..1 MS
* instance.quantity ^short = "Available quantity"

// =====================================================
// EXAMPLES
// =====================================================

Instance: Bioreactor-Algae-001
InstanceOf: BioreactorDevice
Title: "Algae Photobioreactor"
Description: "Closed-loop algae photobioreactor for O2 production and CO2 fixation"
Usage: #example
* insert SyntheticExample

* type.text = "Algae Photobioreactor"
* status = #active
* deviceName.name = "PBR-3000 Photobioreactor #PBR-001"
* deviceName.type = #user-friendly-name
* manufacturer = "Techshot Inc."
* modelNumber = "PBR-3000"
* property[0].type.text = "Volume"
* property[0].valueQuantity[0].value = 50
* property[0].valueQuantity[0].unit = "L"
* property[0].valueQuantity[0].system = $ucum
* property[0].valueQuantity[0].code = #L
* property[1].type.text = "Operating Temperature"
* property[1].valueQuantity[0].value = 25
* property[1].valueQuantity[0].unit = "Cel"
* property[1].valueQuantity[0].system = $ucum
* property[1].valueQuantity[0].code = #Cel
* note.text = "Chlorella vulgaris culture, LED-illuminated, 16h:8h light-dark cycle"

Instance: BLiSS-O2-Production-001
InstanceOf: BLiSSResourceOutput
Title: "BLiSS O2 Production Output"
Description: "Daily O2 production observation from algae photobioreactor"
Usage: #example
* insert SyntheticExample

* status = #final
* code = BLiSSOutputCS#o2-production "O2 Production"
* subject = Reference(Device/Bioreactor-Algae-001)
* effectiveDateTime = "2028-05-15T18:00:00Z"
* component[outputQuantity].code = BiomanufacturingMetricCS#output-quantity "Output Quantity"
* component[outputQuantity].valueQuantity.value = 0.85
* component[outputQuantity].valueQuantity.unit = "kg"
* component[outputQuantity].valueQuantity.system = $ucum
* component[outputQuantity].valueQuantity.code = #kg
* component[outputRate].code = BiomanufacturingMetricCS#output-rate "Output Rate"
* component[outputRate].valueQuantity.value = 0.85
* component[outputRate].valueQuantity.unit = "kg/d"
* component[outputRate].valueQuantity.system = $ucum
* component[outputRate].valueQuantity.code = #kg/d
* component[energyInput].code = BiomanufacturingMetricCS#energy-input "Energy Input"
* component[energyInput].valueQuantity.value = 1.2
* component[energyInput].valueQuantity.unit = "kW"
* component[energyInput].valueQuantity.system = $ucum
* component[energyInput].valueQuantity.code = #kW
* extension[gravityContext].valueCodeableConcept = GravityContextCS#microgravity "Microgravity"

Instance: Biomanufacturing-AlgaeCultivation-001
InstanceOf: BiomanufacturingProcedure
Title: "Algae Cultivation Procedure"
Description: "Chlorella vulgaris cultivation cycle in ISS photobioreactor"
Usage: #example
* insert SyntheticExample

* status = #completed
* code = BiomanufacturingProcessCS#algae-photobioreactor "Algae Photobioreactor"
* subject.display = "International Space Station - Columbus Module"
* performedPeriod.start = "2028-05-01T00:00:00Z"
* performedPeriod.end = "2028-05-15T00:00:00Z"
* usedReference = Reference(Device/Bioreactor-Algae-001)
* outcome = $sct#385669000 "Successful"
* note.text = "14-day cultivation cycle. Harvested 2.1 kg wet biomass, achieving 95% O2 production target."
* extension[gravityContext].valueCodeableConcept = GravityContextCS#microgravity "Microgravity"
