// NAC & Radioprotective Countermeasures
// WP6: Abstract 50 (N-Acetylcysteine), synthesis document

Alias: $loinc = http://loinc.org
Alias: $sct = http://snomed.info/sct
Alias: $ucum = http://unitsofmeasure.org

// =====================================================
// CODE SYSTEMS
// =====================================================

CodeSystem: RadioprotectiveMedicationCS
Id: radioprotective-medication-cs
Title: "Radioprotective Medication Code System"
Description: "Radioprotective and antioxidant medications for space radiation countermeasures"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* ^status = #active
* #nac "N-Acetylcysteine (NAC)" "Antioxidant and glutathione precursor with radioprotective properties"
* #amifostine "Amifostine" "Cytoprotective agent that scavenges free radicals generated by ionizing radiation"
* #vitamin-e-succinate "Vitamin E Succinate (Tocopherol)" "Fat-soluble antioxidant with radioprotective activity"
* #selenium-methionine "Selenium Methionine" "Trace element essential for antioxidant enzyme function"
* #glutathione-precursor "Glutathione Precursor" "Supplements that increase intracellular glutathione levels"

CodeSystem: AntioxidantBiomarkerCS
Id: antioxidant-biomarker-cs
Title: "Antioxidant Biomarker Code System"
Description: "Biomarkers of oxidative stress and antioxidant status"
* ^experimental = false
* ^caseSensitive = true
* ^content = #complete
* ^status = #active
* #glutathione-reduced "Reduced Glutathione (GSH)" "Intracellular reduced glutathione level, primary cellular antioxidant"
* #malondialdehyde "Malondialdehyde (MDA)" "Lipid peroxidation marker indicating oxidative damage"
* #8-ohdg "8-Hydroxy-2'-Deoxyguanosine (8-OHdG)" "Oxidative DNA damage marker"
* #sod-activity "Superoxide Dismutase (SOD) Activity" "Antioxidant enzyme activity level"
* #catalase-activity "Catalase Activity" "Hydrogen peroxide decomposition enzyme activity"
* #tac "Total Antioxidant Capacity (TAC)" "Aggregate antioxidant capacity of biological sample"

// =====================================================
// VALUE SETS
// =====================================================

ValueSet: RadioprotectiveMedicationVS
Id: radioprotective-medication-vs
Title: "Radioprotective Medication Value Set"
Description: "Radioprotective medications for spaceflight"
* ^experimental = false
* ^status = #active
* include codes from system RadioprotectiveMedicationCS

ValueSet: AntioxidantBiomarkerVS
Id: antioxidant-biomarker-vs
Title: "Antioxidant Biomarker Value Set"
Description: "Oxidative stress and antioxidant biomarkers"
* ^experimental = false
* ^status = #active
* include codes from system AntioxidantBiomarkerCS

// =====================================================
// PROFILES
// =====================================================

Profile: RadioprotectiveMedication
Parent: Medication
Id: radioprotective-medication
Title: "Radioprotective Medication"
Description: "Radioprotective and antioxidant medications used as countermeasures against space radiation"
* ^version = "1.0.0"
* ^status = #active

* code 1..1 MS
* code from RadioprotectiveMedicationVS (extensible)
* code ^short = "Radioprotective medication type"

* form 0..1 MS
* form ^short = "Dosage form (oral capsule, IV solution, etc.)"

* ingredient 0..* MS
* ingredient ^short = "Active ingredients for combination formulations"

Profile: RadioprotectiveAdministration
Parent: MedicationAdministration
Id: radioprotective-administration
Title: "Radioprotective Medication Administration"
Description: "Administration of radioprotective medication during space missions, typically timed relative to radiation exposure"
* ^version = "1.0.0"
* ^status = #active

* status MS

* medication[x] 1..1 MS
* medication[x] only CodeableConcept or Reference(RadioprotectiveMedication)
* medicationCodeableConcept from RadioprotectiveMedicationVS (extensible)

* subject 1..1 MS
* subject only Reference(Astronaut)

* effective[x] 1..1 MS
* effective[x] only dateTime or Period

* dosage 0..1 MS
* dosage.route MS
* dosage.route ^short = "Route of administration"
* dosage.dose MS
* dosage.dose ^short = "Dose quantity with units"
* dosage.text 0..1 MS
* dosage.text ^short = "Timing relative to radiation exposure (e.g., 30 min pre-exposure)"

* reasonReference 0..* MS
* reasonReference only Reference(Observation)
* reasonReference ^short = "Link to radiation exposure observation"

* extension contains
    MissionContext named missionContext 0..1 MS and
    GravityContext named gravityContext 0..1 MS

Profile: AntioxidantBiomarkerPanel
Parent: Observation
Id: antioxidant-biomarker-panel
Title: "Antioxidant Biomarker Panel"
Description: "Panel of oxidative stress and antioxidant status biomarkers for monitoring radioprotective countermeasure efficacy"
* ^version = "1.0.0"
* ^status = #active

* status MS
* category 1..* MS

* code 1..1 MS
* code = $loinc#32354-3 "Antioxidants panel"
* code ^short = "Antioxidant status panel"

* subject 1..1 MS
* subject only Reference(Astronaut)

* effective[x] 1..1 MS
* effective[x] only dateTime

* component ^slicing.discriminator.type = #pattern
* component ^slicing.discriminator.path = "code"
* component ^slicing.rules = #open
* component contains
    glutathione 0..1 and
    malondialdehyde 0..1 and
    dnaOxidation 0..1 and
    sodActivity 0..1 and
    catalaseActivity 0..1 and
    totalAntioxidant 0..1

* component[glutathione] ^short = "Reduced glutathione level"
* component[glutathione].code = AntioxidantBiomarkerCS#glutathione-reduced "Reduced Glutathione (GSH)"
* component[glutathione].value[x] only Quantity
* component[glutathione].valueQuantity.system = $ucum
* component[glutathione].valueQuantity.code = #umol/L

* component[malondialdehyde] ^short = "Malondialdehyde lipid peroxidation marker"
* component[malondialdehyde].code = AntioxidantBiomarkerCS#malondialdehyde "Malondialdehyde (MDA)"
* component[malondialdehyde].value[x] only Quantity
* component[malondialdehyde].valueQuantity.system = $ucum
* component[malondialdehyde].valueQuantity.code = #nmol/mL

* component[dnaOxidation] ^short = "8-OHdG oxidative DNA damage marker"
* component[dnaOxidation].code = AntioxidantBiomarkerCS#8-ohdg "8-Hydroxy-2'-Deoxyguanosine (8-OHdG)"
* component[dnaOxidation].value[x] only Quantity
* component[dnaOxidation].valueQuantity.system = $ucum
* component[dnaOxidation].valueQuantity.code = #ng/mL

* component[sodActivity] ^short = "Superoxide dismutase activity"
* component[sodActivity].code = AntioxidantBiomarkerCS#sod-activity "Superoxide Dismutase (SOD) Activity"
* component[sodActivity].value[x] only Quantity
* component[sodActivity].valueQuantity.system = $ucum
* component[sodActivity].valueQuantity.code = #U/mL

* component[catalaseActivity] ^short = "Catalase enzyme activity"
* component[catalaseActivity].code = AntioxidantBiomarkerCS#catalase-activity "Catalase Activity"
* component[catalaseActivity].value[x] only Quantity
* component[catalaseActivity].valueQuantity.system = $ucum
* component[catalaseActivity].valueQuantity.code = #U/mL

* component[totalAntioxidant] ^short = "Total antioxidant capacity"
* component[totalAntioxidant].code = AntioxidantBiomarkerCS#tac "Total Antioxidant Capacity (TAC)"
* component[totalAntioxidant].value[x] only Quantity
* component[totalAntioxidant].valueQuantity.system = $ucum
* component[totalAntioxidant].valueQuantity.code = #mmol/L

* extension contains
    MissionContext named missionContext 0..1 MS and
    MissionPhase named missionPhase 0..1 MS
